#!/bin/bash -l


#SBATCH --nodes 1
#SBATCH --ntasks 1
#SBATCH --cpus-per-task 1
#SBATCH --partition=gpu
#SBATCH --gres=gpu:1
#SBATCH --qos=gpu_free
#SBATCH --mem 8192
#SBATCH --time 2:00:00 



module load gcc/8.4.0-cuda python/3.7.7 mvapich2/2.3.4 opencv/4.2.0-cuda-openmp py-torch/1.6.0-cuda-openmp py-torchvision/0.6.1 py-scikit-learn/0.23.1-openmp    

srun python3 submission.py







 

      
